### PR TITLE
Add AutoGenerateBindingRedirects 

### PR DESCRIPTION
**Pull request by robertkety**
Testing my source control configuration with a minor change to remove a warning

### CODE REVIEW

**Comment by robertkety** [comment]
I checked-in another commit shortly after submitting this PR.  The second commit resulted in build failure and includes an improper git-lfs push.  I closed this because I wanted to try again with a fresh slate.

**Comment by persn** [comment]
You can use force push to completely rewrite the branch. It'll give you the fresh slate effect.

**Comment by robertkety** [comment]
Since we force-pushed #100, it doesn't appear that #99 can reopen.  Should I initiate a fresh PR?

**Comment by persn** [comment]
Sure thing.

**Pull request closed without merging**
