### PR TITLE
Upgrade StyleCop

### PR DESCRIPTION
**Pull request by persn**
The following PR demonstrates how to integrate DotNetAnalyzers/StyleCopAnalyzers into Hero6. #109 I removed the old obsolete StyleCop files, added new ones, I made a minor work-around but I'd rather not discuss until we've discussed everything else in this PR, as the work-around may become obsolete if EmptyKeys gets a patch.

Most of the commits in this PR are fixing code style stuff, as new StyleCop is new and improved and all that it uncovers loads of stuff the old StyleCop was unable to. I've organized the commits so that I resolve each code style issue in each commits, so we can use this opportunity to decide our stance on some rules, and how we should weight them to our preferences as by #121.

TODO:
- [x] Discuss SA1101
- [x] Discuss SA1028
- [x] Discuss SA1116
- [x] Discuss SA1118
- [x] Discuss SA1127
- [x] Discuss SA1128
- [x] Discuss SA1600
- [x] Discuss SA1642
- [x] Discuss SA1636, SA1638, SA1641
- [x] Update PR according to discussions of rules
- [x] Find alternative for d14ed77ea0fca21226676e267355e2cda860206b
- [x] Drop rule SA1609 #131

### CODE REVIEW

**Comment by persn** [comment]
I'll start with SA1101, I'm getting really tired of this rule, I appreciate seeing a variable and knowing it belongs to the class just by seeing the "this" qualifier, however I feel the intense amount of added words to any given code file adds more harm than good, it's not uncommon at all that almost 30% of a single line of code can consists of the "this" qualifier, it's really hard to read.
```
this.test = this.x + this.y;
```
I propose we just code style enforcement of this completely, we don't even need to suggest it.

**Comment by robertkety** [comment]
I'm fine with easing the style requirement for explicit instance reference; however, there are times when it is useful and I think we should reserve that practice for those times.  The combination of static and instance properties and methods in a class are an excellent example of when we should be explicit.

**Comment by persn** [comment]
I'm not sure if StyleCop has a rule for that :) If course the this operator has its place, but we'll either need to find alternative rule sets or we'll have to enforce this manually by peer review on pull requests.

SA1028 This doesn't warrant much discussion I think, removing white space makes for a cleaner code file which makes handling in source control easier and improves useability in low lever text editors,

SA1116 I'm not sure about enforcing this one, maybe set the weighting flag to "Info" instead, I don't feel it's important enough that we should enforce it.

SA1118 I'm all for enforcing this one actually, this is a place where it's super easy to create unreadable code without thinking.

SA1118 I'm not a fan of this one, I just don't see the point, let's drop it from the ruleset.

**Comment by robertkety** [comment]
We could always write some custom StyleCop rules ;)
Joking aside, we should be cautious that we don't spend all our time defining tests and style standards when we could be building the game.  I don't think we've done that here, just trying to avoid what I've observed in other projects.

**Comment by persn** [comment]
After this pull request is done I'm not going to be spending any more time and effort into assessing StyleCop rules unless something comes up that I think is absolute nonsense (which is extremely rare) or someone else raises the issue. I believe this pull request will solve most of our concerns about style enforcement, however I want to do this properly to ensure we don't have to go back to this topic any more than we already have, it's tedious to discuss it.

In this regard, I will be going through each of the style conflicts that was raised by the upgrade just to get ourselves started, doing this also helps making this pull request contents more robust as I discover stuff we want and do not want to do.

So if you could give me a simple yay or nay for the StyleCop rules previously mentioned, unless you have any contradicting opinions, and then we can move along the assembly line and get this matter out of the world as quick as possible. Feel free to share your opinions on the other StyleCop rules on the list as well while I'm afk, just to make this go even faster.

**Comment by robertkety** [comment]
I agree.  Here is my opinion on the following rules.  For the purposes of this post, warnings imply informational feedback to the user on PR and errors imply (but not require) automatic rejection.

SA1028: As an info message, I agree.  Being in the habit of using Ctrl-K, Ctrl-D before commit would prevent that type of style warning.  I think it would be better to inform the PR contributor about that instead of auto-rejecting.
SA1116: I'm fine with that behavior as a warning or an error.
SA1118: I'd be interested to see how this treats lambda expressions, but I'm fine with this as a warning or an error
SA1127: I don't find this very readable.  I'd prefer if we didn't use this rule.
SA1128: I also wouldn't mind dropping this one.  It's very close to something I'd like though. I'd prefer if all on one line initialization was permitted and multi-line initialization required the colon on the same line as the initializer
SA1600: That's fine.  I'd also prefer that this documentation include potentially thrown exceptions as well.
SA1642: This is kind of annoying.  Do we really need to document that a constructor initializes a class?  I feel like this is something that could be applied to the base code at a later date.  To clarify, I like the idea of required documentation, even on ctors, but not with required text.  If I'm typing this out and accidentally rephrase, I'd prefer not to be bothered by the style enforcer.
SA 1636, 1638, and 1641: This is required for licensing purposes.  We should definitely do this.

**Comment by persn** [comment]
Alright, that's a wrap, I pretty much agree with almost everything, or I don't care strongly enough about any individual rule to debate it, pretty much only one issue that I really cared about and we both agreed on it anyways.

I'm going to do some updates to this PR to reflect our new policies and get back to you on how I want to progress with assessing this PR.

In summary if we rank rules from Error, Warning, Info and None:

SA1101 = None
SA1028 = Info
SA1116 = Warning
SA1118 = Warning
SA1127 = None
SA1128 = None
SA1600 = Warning
SA1642 = None
SA1636, SA1638, SA1641 = Warning

I didn't set any of these as errors because.. it feels kinda weird and wrong to classify a style check to return error.

**Comment by persn** [comment]
@robertkety If you could do something.. StyleCopAnalyzers introduces something new, where in addition the rules which are kept in a .ruleset file, they also introduce a .json file with other stuff, so far I've used it to set the contents of our license text and indenting rules. There is a huge list of stuff however that covers other style stuff in addition to the standard rules.

Could you give it a glance and see if there's anything in there you'd like included? https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md

**Comment by persn** [comment]
You approved the PR, I assume this means you didn't find anything worthwhile to add to the .json config file. Does this also mean you've reviewed the contents of the PR and approve of it?

**Comment by persn** [comment]
One thing that concerns me is my hack in 246b23eeb0a436cd7a62a30c0e663176aa96d318, the problem with this is the code file is completely re-written by the EmptyKeys generator every time a re-build is triggered. Meaning the individual developer has to sit and manually make sure the tag is included, which is not at all nice.

The question is how to approach this issue, is there a way to fix this? The old StyleCop had a way to ignore certain files by adding a "IgnoreByStyleCop" or whatever it was called, but I didn't find a working equivalent in the new StyleCop. If such an alternative doesn't exist we may consider if we can live with this problem temporarily, because we probably won't have to deal with it much or for very long. I have filed an issue in the EmptyKeys bug tracker so I'm hoping they'll add StyleCop ignore tags in future versions, however we may also look into just replacing EmptyKeys with something simpler in a near future.

**Comment by robertkety** [comment]
The review just meant that the changes you've committed have been reviewed.  

Which files are you concerned about? Are they auto-generated?  Excluding auto-generated filed should be possible with StyleCop.

**Comment by persn** [comment]
I somehow linked to the wrong commit, I mean this one d14ed77ea0fca21226676e267355e2cda860206b. RootView.xaml.cs is auto-generated by EmptyKeys from the file RootView.xaml, the tag you see in the commit is how StyleCop ignores auto-generated files, however that does us no good since the tag disappears into the ether every time the EmptyKeys generator is triggered.

**Comment by persn** [comment]
I fixed this with the previous StyleCop, because it supported an extra tag in .csproj which looks like this

```
<Compile Include="View\RootView.xaml.cs">
    <ExcludeFromStyleCop>True</ExcludeFromStyleCop>
</Compile>
```

It doesn't looks as if StyleCopAnalyzers support this however.

**Comment by persn** [comment]
Seeing as StyleCopAnalyzers runs as a Visual Studio Code Analyzer it would follow the same rules, the project this file is in even has the option "Suppress results from generated code". But in order for this to work we would need some way to tell the analyzer that our file is generated, which is missing. I'm not having much success in googling this.

**Comment by persn** [comment]
After I've been googling my butt off it turns out this exact problem has resulted in Roslyn getting a lot of unfavorable attention from users, and they've been struggling with it since 2015.. A lot of the issues seems to be based around the core that there's no conventional way to actually mark a file as auto-generated, historically in the C# world all kinds of wacky solutions has been implemented to do this, but no set single solution used by all is still in place.

I'm not sure where to go from here

**Comment by persn** [comment]
The author of EmptyKeys replied to my bug ticket and said that next version will be StyleCop compatible, we still don't know when next version is going to come out however.

**Comment by robertkety** [comment]
I added a comment to that bug ticket as well.  My hope is that his solution provides for custom comment headers so we can add other metadata like our standard file header.

**Comment by persn** [comment]
@robertkety I ended up requesting a new review since I had to remake the entire Pull Request from scratch, certain commits have now disappeared completely as they weren't relevant anymore, but also completely new commits like 23c5c5e has appeared. Most of the stuff here however you've already seen before so I'm not entirely fuzzed if you end up skimming through the entire thing.

This is pretty much ready to to be merged as far as I am concerned, I would however ask that you put some  serious thought into if there's anything else we need to do regarding this Pull Request, if there's more we need to do regarding code style enforcement and the like, as I'm hoping that after this we never go back to the topic of code style. Of course there are exceptions, raising a new issue to discuss whether we should enforce individual rules should be okay.

**Pull request merged**
