### PR TITLE
Player stats with unit tests

### PR DESCRIPTION
**Pull request by persn**

### CODE REVIEW

**Comment by persn** [comment]
The entire purpose of the campaign scope stat cap is to increase it for sequels/expansions, like Quest for Glory did. You say you want to set it on character-by-character basis.. Why?

**Comment by robertkety** [comment]
My comment above is misleading.  I see the reasoning behind a campaign-wide stat cap. I think we're on the same page with that.  I do think we should set a character stat cap as well.  This would allow designers to cap the maximum difficulty of specific foes in a combat scenario (e.g., no epic-level goblins - they can get tougher, but never to the same level as a player character).  It could also be used in a game mechanic scenario like when opposing calculating outcome based on stat comparison (e.g., a bluff vs. another's ability to sense deceit).

**Comment by persn** [comment]
Does that have any bearings on this pull request or are you just mentioning it because as a topic it is vaguely related to stat caps? The feature you're describing sounds awfully like something no one except a few special interested would use, in the result of more clutter to our code base, which means we're not going to implement it by default. It's a framework, people are free to extend it with their own custom logic after all.

At any rate, I can't see that this is relevant for the PR at hand, enemies will most likely not have the same implementation as PCs. If you don't believe this needs to be dealt with now you can raise a new issue for it, because it will just be forgotten in this conversation.

**Comment by robertkety** [comment]
It was purely conversational.  I was looking for your thoughts.  It wasn't intended to block the PR

**Comment by persn** [comment]
Aha! Well I feel this isn't something we're going to use or needs to be implemented for Hero6. If anyone want to use our framework but desire special functionality they're free to extend and modify it. Isn't that the trait of a good framework? Robust skeleton, easy to add muscle and flesh.

**Comment by persn** [comment]
I requested a new review because I had to do some stuff after the changes brought in by the the recent PR merges.

**Pull request merged**
