### PR TITLE
#10 Support for Localization

### PR DESCRIPTION
**Pull request by persn**
Added .resx files to our campaign. This should be satisfactory for supporting multiple languages. It's not quite clear since we have so little content at this point, but my intention is that each plugin will have to provide their own "Strings.resx", I think this is the best way to make sure we support various locales when we support extending the game from third parties.

### CODE REVIEW

**Comment by persn** [comment]
I updated the commit message with more details.

**Comment by robertkety** [comment]
Interesting solution for storing these values.  How are you generating the resx files, by hand?

**Comment by persn** [comment]
Are you asking me how I add, edit and remove entries from the resx files? I'm using the Visual Studio Editor.

untitled

**Comment by robertkety** [comment]
Cool! I've seen a few projects built using resx, but haven't made time to examine it any further.  I'm surprised so much metadata surrounds what is essentially name-value pairs (or name-value-comment triads 👍)

**Comment by persn** [comment]
Do you want me to quickly translate the strings to Norwegian in a mock up branch? That way you can see how supporting multiple languages work with resx files.

**Comment by robertkety** [comment]
I think that's a terrific idea.  Not just for my own curiosity, but as a practical example for future code contributions.

**Comment by persn** [comment]
This branch demonstrates rough and easy how to implement a new language into the game, and also there's a small line of code in there that shows how easy it is to actually change the locale in the software. If you check out the branch, build and run, you'll also see that it works flawlessly in-game, including Norwegian special characters like 'Å'.

https://github.com/persn/Hero6/tree/develop/feature/mock-localization

untitled

**Comment by persn** [comment]
Any language that is not considered the default language of the software will be compiled in separate assemblies organized neatly into folders, folders are named by locale codes, which makes it quite easy to support multiple languages in our game as add-ons.

untitled

**Pull request merged**
