### PR TITLE
Rest GUI

### PR DESCRIPTION
**Pull request by persn**
Fixes a small bug and adds a GUI dialog for resting options

### CODE REVIEW

**Comment by persn** [comment]
> For Label.cs, are we only handling text wrapping when height or width == -1?

Did you check out the code file in its entirety or did you just check the diff? What you see on the diff is only initialization, we have other code handling text wrapping in the rest of the file. I'm using -1 as a way to check if the UI elements width and height are uninitialized from outside coders, if it is set to -1 it we set them to proper values ourselves.

> Why are these in two different conditionals?

Ehh, I don't understand the question. Because they're two separate properties and therefore also needs to  be handled separately?

> Are you planning on further implementation?

I'm not really planning anything, building a UI framework from scratch is bitching work, it's a task I was hoping to avoid, and I'm not sure my experience is sufficient to build a good one. I'm kinda just moving forward, seeing what breaks, and fixes the problems as I find them as well as I can with emphasis on doing it as well as possible for each "iteration". Wouldn't want to come to alpha/beta stages and find ourselves locked in with a framework that's hard to work with.

**Comment by robertkety** [comment]
I remember using -1 in my Linux coding days as an error code. I was just confirming if that's what you were doing. In the now times I'm not a big fan of magic numbers, but that's a personal preference, not a guideline for others to follow.


The multiple conditional question was just a recommendation. Each conditional is doing the same thing (if I remember correctly). We could have put both conditions in the same if statement and prevented duplicate code. However, that's only a good idea if we're planning on using the same default behavior for both cases. Again, this all the conversational in nature, no criticism intended.


On Sat, May 20, 2017 at 10:43am, Per Olav Flaten < notifications@github.com [notifications@github.com] > wrote:
For Label.cs, are we only handling text wrapping when height or width == -1?

Did you check out the code file in its entirety or did you just check the diff? What you see on the diff is only initialization, we have other code handling text wrapping in the rest of the file. I'm using -1 as a way to check if the UI elements width and height are uninitialized from outside coders, if it is set to -1 it we set them to proper values ourselves.

Why are these in two different conditionals?

Ehh, I don't understand the question. Because they're two separate properties and therefore also needs to be handled separately?

Are you planning on further implementation?

I'm not really planning anything, building a UI framework from scratch is bitching work, it's a task I was hoping to avoid, and I'm not sure my experience is sufficient to build a good one. I'm kinda just moving forward, seeing what breaks, and fixes the problems as I find them as well as I can with emphasis on doing it as well as possible for each "iteration". Wouldn't want to come to alpha/beta stages and find ourselves locked in with a framework that's hard to work with.

**Comment by persn** [comment]
> I'm not a big fan of magic numbers

Well I'm not a fan either, but what would be the clean work around? I'll experiment a little and see if I can come up with something clever.

> We could have put both conditions in the same if statement and prevented duplicate code.

I'm going to have to ask you for a quick code mockup because you're making zero sense. I can probably avoid code duplication by introducing a helper function (which is a very good idea actually)
```
private void SetDimension(ref int dimension)
```
but that has nothing to do with what you're saying about if-statements.

**Comment by persn** [comment]
I made a new fix so that we no longer use -1, please give it a look

**Comment by persn** [comment]
I rebased on master because everything broke

**Comment by robertkety** [comment]
I've reviewed this PR.  Everything looks ready for merge.

**Pull request merged**
